site_name: Computer Architecture & Organization Labs
site_url: http://scu-ccs-coa-labs.github.io
site_author: Tiger1218
theme:
  name: material

nav: 
  - Overview: index.md
  - Experimental Environment:
    - Environment Overview: envs/index.md
    - git Configure: envs/git.md
    - Python Configure: envs/python.md
  - About: about.md
  - Labs:
    - Lab Overview: labs/index.md
    - Cache Lab: labs/cache.md
    - IEEE 754 Lab: labs/ieee754.md
    - CRC Lab: labs/crc.md
    - Booth Lab: labs/booth.md
  - Projects:
    - Project Overview: projects/index.md
    - SCUBA: projects/scuba.md




markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
